### ISSUE TITLE
Segatools "ERROR(3) #6507 NFC R/W Initialize Fault."

### ISSUE THREAD

**Issue by FusionFernia0000** [Sucareto/Arduino-Aime-Reader#1]
测试环境: 中二水晶, 换了chunihook.dll , segatools.ini 中 [aime] enable=0 , Arduino Micro在COM12, LED发蓝光

测试菜单中 Aime 读卡器 在1.3~1.5秒后显示BAD, inject.exe 显示 "ERROR(3) #6507 NFC R/W Initialize Fault."

PN532 SDA -> Arduino Micro Pin 2
PN532 SCL  -> Arduino Micro Pin 3
PN532 VCC -> Arduino Micro VCC
PN532 GND -> Arduino Micro GND
APA106 LED -> Arduino Micro A3

![Screenshot (5)](https://user-images.githubusercontent.com/20417687/119102137-48682e00-ba4c-11eb-8ec5-459c800c1291.png)

**Comment by Sucareto** [comment]
Arduino Micro = [SparkFun Pro Micro](https://learn.sparkfun.com/tutorials/pro-micro--fio-v3-hookup-guide/hardware-overview-pro-micro)?
自检过程中，Arduino的RX和TX灯是否有闪烁？
如果没有，可能是需要发送DTR/RTS。
请在连接Arduino后打开一次Arduino IDE的串口监视器（以38400波特率打开）；
或者运行一次[DTR-RTS.exe](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/DTR-RTS.exe)。

**Comment by FusionFernia0000** [comment]
[Arduino Micro](https://store.arduino.cc/arduino-micro)是这种
在Device Manager內把COM12改成38400, 检查沒其他東西占领COM12, 再跑DTR-RTS就ok了, 3.5秒可读卡
