### ISSUE TITLE
想把卡写入手机里，但不太看得懂是怎么做到读出aime卡数据的

### ISSUE THREAD

**Issue by LingBai0703** [Sucareto/Arduino-Aime-Reader#10]
卡，pn532，promicro都有，但之前用普通工具直接读读不出来，但给的aime示例和读卡方式都看不太懂，望大神指点（

**Comment by Sucareto** [comment]
普通工具读不出来的原因是扇区有加密。
key：
```
aime:574343467632
bana:6090D00632F5
```
使用以上密钥应该就可以读写了。
[Aime 卡示例](doc/aime示例.mct)的数据是使用 [MifareClassicTool](https://github.com/ikarus23/MifareClassicTool) 提取的，你也可以用这个软件进行读写。
但如果你要把数据写入手机的 NFC，那就得需要用别的方法了。

我的方法是：将 PN532 调为 HSU 模式，用“USB-TTL 连接线”连接到电脑，使用 [MifareOneTool](https://github.com/xcicode/MifareOneTool) 连接，就可以进行读卡写卡操作了。
先在 NFC 随便生成一张空白卡，然后把 [Aime 卡示例](doc/aime示例.mct) 修改完成后写入，再读取一遍查看是否成功。

类似的方法有很多，你可以搜索“手机 NFC 复制加密卡”就能找到相关内容。
如果打算做 Arduino 读卡器的话，我的建议是使用 ESP32 或者 ESP8266，因为便宜，而且还可以当作“USB-TTL 连接线”来使用。

**Comment by LingBai0703** [comment]
谢谢您的指点，已经成功读取出了卡数据，但我对于aime卡事例还有个小小的疑问，修改的话是直接修改掉整个0扇区部分还是只修改第一行的厂家块和第三行的卡号？

**Comment by Sucareto** [comment]
第一行的数据没影响，真正的卡号是在[第三行](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/doc/aime%E7%A4%BA%E4%BE%8B.mct#L4)的`10114514191981023333`这一段，和游戏里的 Access Code 是一样的。
只修改这一段卡号就可以，其他的数据不用动都无所谓，手机 NFC 也没法完整复制厂家块的数据，所以不管就好。

**Comment by LingBai0703** [comment]
感谢您的指点，但我还有个小问题，如果是aic的话可以复制进手机吗？

**Comment by Sucareto** [comment]
据我了解，是不行的，因为 mifare 和 felica 标准不一样，手机的 nfc 芯片不一定支持。

**Comment by LingBai0703** [comment]
好吧，看了勤港澳台还是要带卡，感谢您的帮助啦
