### ISSUE TITLE
请问我可以直接转成串口通信吗

### ISSUE THREAD

**Issue by HereXianggeGe** [Sucareto/Arduino-Aime-Reader#11]
如题，想改成能在机台上使用的读卡器。

**Comment by Sucareto** [comment]
可以的，固件是支持官机的。找到合适的方法连接到机台即可。

**Comment by HereXianggeGe** [comment]
直接用rs232转usb的线就ok吗，还是需要走FT232之类的小板？

**Comment by Sucareto** [comment]
RS232 的接线我不太了解，应该可以使用 `RS232 转 TTL` 之类的模块连接单片机的 `RX` 和 `TX` 使用。
如果是适配列表里的 `ATmega32U4` 和 `ATSAMD21G18`，需要将代码里的 `SerialDevice` 定义为 `Serial`。
如果框体没屏蔽 USB 的话，可能是 USB 方式比较简单。

**Comment by HereXianggeGe** [comment]
主要游戏SDFE会检测aime读卡器，没有的话启动不了，而基板不允许装驱动，所以直接走串口貌似是最便捷的。
改成Serial后通信就会走片上的RX TX口了是吗，我试试用转接器看看基板能不能读出来。谢谢大佬！

**Comment by Sucareto** [comment]
好诶，期待你的测试结果~
