### ISSUE TITLE
DFRobot Uno下，使用ReaderTest测试通过，但使用Aime-Reader测试时不通过。

### ISSUE THREAD

**Issue by UzLung1435** [Sucareto/Arduino-Aime-Reader#12]
如题。
使用DFRobot Uno R3+PN532测试。使用ReaderTest时能正常读出卡号。
![image](https://github.com/Sucareto/Arduino-Aime-Reader/assets/27557591/b2426701-2f28-4609-b2d4-d78c52424d1c)

看过以往的issues发现[Arduino Uno & Raspberry Pi Pico 无反应](https://github.com/Sucareto/Arduino-Aime-Reader/issues/8l)这个issue下有相关内容。但实际操作后发现似乎有异常（？）

测试了SDHD 1.20，cvt框体下使用38400波特率没有反应。切换到sp模式后依旧无反应。
测试了SDEZ 1.30，也是无反应。
在刷卡界面时，开发板上的TX/RX指示灯并未闪烁。

使用的代码是最新的，把不符合该单片机的配置代码删掉了。

**Comment by Sucareto** [comment]
查了下[DFRduino UNO R3](https://www.dfrobot.com/product-838.html)的介绍，串口芯片是 `ATmega16U2`，和那个帖子的情况可能不太一样。
是否尝试过启动前运行一次 [DTR-RTS.exe](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/DTR-RTS.exe)？
如果仍然无效，可以用串口调试工具手动发包检查固件是否正常工作，或者使用串口抓包工具抓一个记录我分析看看。

**Comment by UzLung1435** [comment]
试了一下。不知道是否与我目前在用的Brokenithm有冲突。
使用Device Monitoring Studio进行监控发现完全没有数据传输。应该是我的软件设置问题。
那假如说我需要这样的刷卡功能那我应该怎么做（？） ~~如果你愿意细说并且不违反某些条例的话~~

**Comment by Sucareto** [comment]
> 测试了SDHD 1.20，cvt框体下使用38400波特率没有反应。切换到sp模式后依旧无反应。 测试了SDEZ 1.30，也是无反应。 在刷卡界面时，开发板上的TX/RX指示灯并未闪烁。

没有反应的具体情况是？游戏的读卡器自检是否有通过？

> 使用Device Monitoring Studio进行监控发现完全没有数据传输。应该是我的软件设置问题。

`amdaemon.exe` 打开串口相关的操作有出现吗？

> 试了一下。不知道是否与我目前在用的Brokenithm有冲突。

有可能使用了修改版的 `segatools` 会接管读卡器相关功能。
在 `segatools.ini` 内添加以下内容：
```
[aime]
enable=0
```
然后在不接入读卡器的状态下，启动游戏程序。如果读卡器自检报错，那 `segatools` 功能正常，再接入读卡器重启游戏试试看。



> 那假如说我需要这样的刷卡功能那我应该怎么做（？）

如果只是简单的需要给游戏提供不同卡号用于区分多人账号，可以使用别的方案，例如：
- 使用一个程序通过某种方式获取卡号（如摄像头、或者自定义单片机通讯数据），然后更改 `DEVICE` 目录的卡号文件
- 修改 `segatools` 读卡部分源码，自定义通讯方式（比较困难，适合制作手台等需求）

如果实在是需要刷多种类型的实体卡，或者想要使用官机的方式读卡，只能根据情况更换合适的 `segatools` 或者读卡器硬件来达成这个目标。
本项目主要目的是实现兼容官机且可以自定义的读卡器，对于普通的读卡需求，或许并不是最优解。

**Comment by UzLung1435** [comment]
终于抽了点时间出来对比了Broeknithm中[Hook for New](https://github.com/tindy2013/Brokenithm-Android-Server/releases/tag/new-hook)的实现，发现hook默认使用 `emulate aime device ` 从而导致不使用实体aime device. 而在 `segatools.ini` 中指定 `aime=0` 后，aime被禁用且无法访问到实体aime设备。

所以我的实体手台也在路上了，或许我可以先试着修改hook来改进这个刷卡（？）

基于这点我关闭了在 `SDEZ 1.30` 下的 `Aime Emulation` （也就是您上述提及的有关aime的那行），成功访问到实体aime并读取卡号。
再次感谢您的解答TT

**Comment by HeimaoLST** [comment]
> 终于抽了点时间出来对比了Broeknithm中[Hook for New](https://github.com/tindy2013/Brokenithm-Android-Server/releases/tag/new-hook)的实现，发现hook默认使用 `emulate aime device ` 从而导致不使用实体aime device. 而在 `segatools.ini` 中指定 `aime=0` 后，aime被禁用且无法访问到实体aime设备。
> 
> 所以我的实体手台也在路上了，或许我可以先试着修改hook来改进这个刷卡（？）
> 
> 基于这点我关闭了在 `SDEZ 1.30` 下的 `Aime Emulation` （也就是您上述提及的有关aime的那行），成功访问到实体aime并读取卡号。 再次感谢您的解答TT

想请教一下如何修改这个hook呢 我与你有相似的问题 感谢
