### ISSUE TITLE
关于aime卡的读取问题

### ISSUE THREAD

**Issue by HeimaoLST** [Sucareto/Arduino-Aime-Reader#13]
虽然有挖坟的嫌疑但是还是想请教一下

现在我手里的aime卡是Felica，而不是mifare。 在这种情况下，我仍然可以通过写入修改后的所提供的aime示例数据来实现正常登录吗？
同时也想问问如何可以读取我手里这张felica aime卡的数据?

**Comment by Sucareto** [comment]
你提到的 FeliCa 版的 Aime 卡是 Amusement IC，并不是 MIFARE 的，那个 Aime 卡示例文件是用于 MIFARE 的，这两者并不是同一种卡。

Sega 游戏用于登录的数据是 ACCESS CODE，可以在卡的背面找到，或者在游戏登录的菜单中看到。
如果想实现 MIFARE 和 FeliCa 登录同一个账号，那你可以把 FeliCa 的 ACCESS CODE 替换到 Aime 卡示例文件，然后写入 MIFARE 卡。

Amusement IC 是 FeliCa 卡片，使用支持 FeliCa 的读卡软件就可以读到里面的数据。

**Comment by HeimaoLST** [comment]
首先感谢大佬回答。我那张卡上就是那种常见的蓝白卡 上面有aime的字样 同时也有 Amusement IC的标志，我就把它当aime卡了。目前我已经成功将我原来的ACCESS CODE写入一张MIFARE卡。

**Comment by Sucareto** [comment]
将 ACCESS CODE 按照 [Aime 卡示例](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/doc/aime%E7%A4%BA%E4%BE%8B.mct) 的格式写入 MIFARE 卡，可以让游戏读取到，但某些严格校验的游戏可能不支持这种方式。如果在登录界面查看 ACCESS CODE 是正确的话，应该就没问题了。
