### ISSUE TITLE
SDHD游戏自检Aime项BAD

### ISSUE THREAD

**Issue by HeimaoLST** [Sucareto/Arduino-Aime-Reader#14]
使用开发板为NodeMCU-32S，readertest可以正常读到卡片类型以及数据。
但是烧录主程序后进游戏无法过Aime自检 segatools已修改 
想请教一下如何找出问题

**Comment by HeimaoLST** [comment]
手动发了一下包 有
![image](https://github.com/Sucareto/Arduino-Aime-Reader/assets/88563908/d3021f7e-620e-4b4a-998a-9941e3b03a63)响应 可能是软件有问题

**Comment by Sucareto** [comment]
NodeMCU-32S，用的是 CH340 的版本吗？
手动发包正常的话，读卡器固件是没问题的。
使用 [Serial Port Monitor](https://www.electronic.us/products/serial-port-monitor/) 或者类似的串口监控软件，检查游戏有没有正常打开串口设备？

SDHD 的话，会分为 cvt 和 sp 两种模式，这两种模式下读卡器都是 COM4，但是波特率并不一样。
如果是 cvt 模式，那么和 SDBT 一样，需要将代码里的 `#define high_baudrate` 注释掉。

**Comment by HeimaoLST** [comment]
> NodeMCU-32S，用的是 CH340 的版本吗？ 手动发包正常的话，读卡器固件是没问题的。 使用 [Serial Port Monitor](https://www.electronic.us/products/serial-port-monitor/) 或者类似的串口监控软件，检查游戏有没有正常打开串口设备？
> 
> SDHD 的话，会分为 cvt 和 sp 两种模式，这两种模式下读卡器都是 COM4，但是波特率并不一样。 如果是 cvt 模式，那么和 SDBT 一样，需要将代码里的 `#define high_baudrate` 注释掉。

用串口软件看了一下 游戏启动过程中com4串口没有任何响应 尽管我已经修改了segatools

**Comment by HeimaoLST** [comment]
这么看来似乎游戏没有调用实体读卡器

**Comment by HeimaoLST** [comment]
> 这么看来似乎游戏没有调用实体读卡器



> > NodeMCU-32S，用的是 CH340 的版本吗？ 手动发包正常的话，读卡器固件是没问题的。 使用 [Serial Port Monitor](https://www.electronic.us/products/serial-port-monitor/) 或者类似的串口监控软件，检查游戏有没有正常打开串口设备？
> > SDHD 的话，会分为 cvt 和 sp 两种模式，这两种模式下读卡器都是 COM4，但是波特率并不一样。 如果是 cvt 模式，那么和 SDBT 一样，需要将代码里的 `#define high_baudrate` 注释掉。
> 
> 用串口软件看了一下 游戏启动过程中com4串口没有任何响应 尽管我已经修改了segatools

游戏为sp模式

**Comment by HeimaoLST** [comment]
[Arduino-Aime-Reader-ver1.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/13326035/Arduino-Aime-Reader-ver1.zip)
我修改了一部分关于LED的代码 应该不会影响到与游戏的通信

**Comment by Sucareto** [comment]
> 用串口软件看了一下 游戏启动过程中com4串口没有任何响应 尽管我已经修改了segatools

在 segatools.ini 内填入以下内容，可以禁用掉 segatools 自带的读卡器模拟：
```
[aime]
enable=0
```

禁用了读卡器模拟后，游戏会直接和实体读卡器进行通信，COM 的序号在 config_sp.json 或者 config_cvt.json 内有定义：
```
"aime" :
    {
        "enable" : true,
        "unit" :
        [
            {
                "port" : 4,
                "id" : 1
            }
        ],
        "high_baudrate" : true
    }
```
`aime -> unit -> port -> 4`，这里是 COM4，`"high_baudrate" : true` 对应代码里的 115200 波特率。
检查这部分设置是否被修改，而且有可能 segatools 未正确设置 sp、cvt 框体模式，可以修改读卡器代码里的 high_baudrate 设置再试试看。

在不使用实体读卡器的情况下，进游戏的读卡器自检，会检测不到固件号，执行读卡测试也会马上 bad。
如果还能读到固件号，那可能是使用的 segatools 修改了这部分逻辑，具体的使用方法需要询问这份 segatools 的开发者。

> [Arduino-Aime-Reader-ver1.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/13326035/Arduino-Aime-Reader-ver1.zip) 我修改了一部分关于LED的代码 应该不会影响到与游戏的通信

不应该注释掉 `sys_get_led_info()` 函数的调用，这会导致游戏获取不到读卡器 LED 固件的信息。
如果在使用的硬件没有或者不需要 LED，可以注释掉 FastLED 相关语句，或者把 LED_PIN 改成一个没在用的针脚就行。
