### ISSUE TITLE
ESP32-S 使用 I2C 接线时 SDEZ Aime reader 测试BAD

### ISSUE THREAD

**Issue by OctoFlareDev** [Sucareto/Arduino-Aime-Reader#16]
可以正常读取硬件固件版本号

不插读卡器在测试时1.0s BAD
插读卡器会时间长一些 BAD
进游戏显示Aime不可用
使用ESP WROOM 32 CH340
使用I2C连接
使用Flipper Zero模拟Aime卡
ReaderTest正常，可识别模拟的Aime卡
![image](https://github.com/Sucareto/Arduino-Aime-Reader/assets/62318879/d6673746-7003-42e8-9917-db8732164261)

**Comment by Sucareto** [comment]
是用最新版本的代码嘛？有对代码进行了哪些修改？
在读卡器测试界面，切换 LED 是否有生效？

**Comment by OctoFlareDev** [comment]
是最新版本
因为用I2C连接所以注释掉了SPI pin
因为我没有灯条所以将fastled代码换成了tone
在游戏里更改LED有反应

**Comment by OctoFlareDev** [comment]
补充：用I2C连接是因为不知道SPI的接线

**Comment by Sucareto** [comment]
在测试界面读不到卡大概是 10s 左右会 BAD，能读到固件号，ESP32 应该是正常工作了。
即使没有灯条，也可以使用带 FastLED 的代码，不会影响效果，可以恢复到默认代码试试看。
还有的可能是 PN532 连接不正常？如果有串口调试工具，开始尝试手动发包调试一下。

SPI 的接线，参考如下：
PN532       ESP32
SCK   ----- VSPI SCK (GPIO18)
MISO  ----- VSPI MISO (GPIO19)
MOSI  ----- VSPI MOSI (GPIO23)
SS    ----- VSPI SS (GPIO05,PN532_SPI_SS 定义的)
VCC   ----- VIN 3.3V
GND   ----- GND

**Comment by OctoFlareDev** [comment]
用I2C连接的时候readertest是可以正常读取的

使用SPI接线后游戏内工作正常

**Comment by Xenon-XG** [comment]
@OctoFlareDev 你好，我也遇到了和你一样的问题，可以请教一下怎么解决在i2c模式下游戏测试bad的问题
