### ISSUE TITLE
About SDDT Felica

### ISSUE THREAD

**Issue by senzi96** [Sucareto/Arduino-Aime-Reader#2]
大佬您好，我们用Pro micro写入了固件（led变成黄色）SDDT游戏下aime正常读取，但是Felica（aic）读取失败，使用iPhone nfc suica卡（Felica规格），游戏读取到的卡号全部都是F。请问一下可能是哪里的问题

**Comment by senzi96** [comment]
> 大佬您好，我们用Pro micro写入了固件（led变成黄色）SDDT游戏下aime正常读取，但是Felica（aic）读取失败，使用iPhone nfc suica卡（Felica规格），游戏读取到的卡号全部都是F。请问一下可能是哪里的问题

顺便说一下我们的SDDT是1.25-J版本

**Comment by Sucareto** [comment]
试一下这个：[ReaderTest](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest.ino)
测试一下有没有成功读到 Felica？

**Comment by Niumx** [comment]
Pro micro下音击不支持felica，只支持aime，
esp8266在音击下不识别读卡器，中二正常。
SAMD21和Pro micro一样，音击不支持felica，只支持aime

**Comment by Sucareto** [comment]
> Pro micro下音击不支持felica，只支持aime， esp8266在音击下不识别读卡器，中二正常。 SAMD21和Pro micro一样，音击不支持felica，只支持aime

使用楼上的测试程序，能正常读到卡吗？

**Comment by Sucareto** [comment]
> Pro micro下音击不支持felica，只支持aime， esp8266在音击下不识别读卡器，中二正常。 SAMD21和Pro micro一样，音击不支持felica，只支持aime

测试过了，Pro micro 和 esp8266 都可以支持音击和中二，Aime 和 Felica 都可以正常读。
音击需要设置正确的端口，以及根据`high_baudrate`的开关来设置正确的波特率。
