### ISSUE TITLE
想手表和手机录入banapassport卡，但是0扇区第一行始终不对

### ISSUE THREAD

**Issue by MNB-54188** [Sucareto/Arduino-Aime-Reader#20]
![IMG_20240930_212021](https://github.com/user-attachments/assets/37e1a733-8f7f-4d80-a739-6664f6977026)
湾岸终端机显示，该banapassport卡不可用
求助大佬

**Comment by Sucareto** [comment]
[MIFARE](https://zh.wikipedia.org/wiki/MIFARE) 卡的 0 扇区第一行被称为厂商块，储存了卡号和厂商信息，常规的 MIFARE 卡并不支持修改，需要使用 CUID 或 FUID 等类型的卡片才可以写入。
一般手机和手环模拟卡并不支持修改这部分，可以去搜索相关的门禁卡复制教程来了解具体情况。

**Comment by MNB-54188** [comment]
使用cuid卡复制进手表，再写入卡号。
这个方法可行吗

**Comment by Sucareto** [comment]
> 使用cuid卡复制进手表，再写入卡号。

具体是指怎么操作？

据我所知，手环/手机 NFC 复制现有卡片时，厂商块仅会复制 UID 部分，后面部分是不会复制的，后续再通过读卡器设备写入/修改也无效。
而 CUID 卡是可以完全修改/写入的。

**Comment by MNB-54188** [comment]
我的方法是
先将banapassport原卡数据录入cuid，再用手表复制cuid卡，再尝试写入uid。

**Comment by Sucareto** [comment]
> 我的方法是 先将banapassport原卡数据录入cuid

CUID 卡如果复制写入成功，那这张 CUID 卡等同原卡，可以在使用。

> 再用手表复制cuid卡

手表复制原卡或 CUID 卡是一样的，没有任何区别。

> 再尝试写入uid

上面已经提到了，手表/手环/手机 NFC 复制现有卡片时，**手表/手环/手机 NFC 模拟的卡片厂商块仅会复制 UID 部分**，后面部分的其他数据是不会复制的，之后也无法修改/重新写入。

或许你的设备不一样？你可以试试看。

**Comment by MNB-54188** [comment]
好的，已经了解了，感谢大佬
