### ISSUE TITLE
aimeReaderHost:Incompatible Card(#28)

### ISSUE THREAD

**Issue by ShiroAsrm** [Sucareto/Arduino-Aime-Reader#3]
使用Pro Micro在SDBT上尝试刷banapass的时候aimeReaderHost提示不兼容
已经使用ReaderTest测试可以读取
不清楚问题是如何产生的 曾经使用八达通和aime卡都可以读取
信息可能提供不全 麻烦您了

**Comment by Sucareto** [comment]
这个问题我也遇到过，貌似是banapass的block 2的数据不符合要求
banapass的密钥是6090D0CF0632F5，你可以尝试读取block 2，截取后20位放到aime.txt里面，禁用物理读卡器试试看
ReaderTest默认可以读取block 2然后在串口打印，或者可以用以下软件读取：
[PC端：MifareOneTool](https://github.com/xcicode/MifareOneTool)
[Android端：MIFARE Classic Tool (MCT)](https://github.com/ikarus23/MifareClassicTool)
如果仍然不行，那大概是卡片或者其他原因了
我这边只有一张未使用的banapass，也是无法使用，不知道是否需要开卡或者什么操作

**Comment by ShiroAsrm** [comment]
应该是卡block的问题,uid的话应该是可以强制转换出来的

**Comment by Sucareto** [comment]
之前分析了aime卡和官机读卡器的通讯数据，发现block 2是纯数字的，但我新购买的未使用banapass，block 2里面是带有FF这样的hex数据，或许是需要写卡吧...
如果有办法找到一张已使用的banapass看下数据就好了~

**Comment by Sucareto** [comment]
banapass似乎使用了不同的读取和认证方式，目前没有官方读卡器的串口数据用于分析，已移除对banapass的支持。

**Comment by Sucareto** [comment]
最新版本已支持banapass。
