### ISSUE TITLE
SDDT felica

### ISSUE THREAD

**Issue by senzi96** [Sucareto/Arduino-Aime-Reader#5]
SDDT刷suica时会弹窗显示C++报错，请问可能是什么问题
![IMG_3714](https://user-images.githubusercontent.com/68644143/151676385-77150720-588f-4469-9d67-6ecbb0145007.JPG)

**Comment by Sucareto** [comment]
不使用实体读卡器的情况下刷卡会报错吗？
关闭emoney功能试试看？

**Comment by Sucareto** [comment]
SDDT和SDEZ同样使用amdaemon，已测试没有发现问题。
可能是amdaemon主程序的问题？如果测试的确是因为读卡器报错的话，请提供更多的信息。
