### ISSUE TITLE
SDDT aic闪退

### ISSUE THREAD

**Issue by senzi96** [Sucareto/Arduino-Aime-Reader#7]
请问我们这边有少量aic卡（蓝白aic和konami红白aic都有）打完一首歌后在SDDT中点击继续下一首时必定闪退可能是什么问题，如果只玩一首后直接结束则不会。经测试这些aic卡片在在线和本地aqua中刷卡都会有这种问题。附上日志

SET TIMEOUT :0 Port:1 Unit:-1 PL:2
22/03/06 17:19:37 AimeLog Result:0
22/03/06 17:19:37 startSendAimeLog result:0
s_pAiMeDB threadFlag :0000016DC39A7914 
m_pTCPSock Adr:0000016DC376E290
AiMeDB: Thread Start
s_pAiMeDBClient Adr:0000016DC39CA590 
resolving : aime.naominet.jp
22/03/06 17:19:37 getaddr start!!
resolved  : 8.210.94.234
AimeLogSend ThreadFunc
AimeLogSend
WSA LastErr:10035
.WSA LastErr:10037
.WSA LastErr:10037
.WSA LastErr:10037
.WSA LastErr:10037
.WSA LastErr:10037
..........
AimeLogSend Result=0
22/03/06 17:19:37 ALIVE THREAD:1
22/03/06 17:19:37 AiMeDB: Thread Exit
22/03/06 17:19:37 3sec WAIT Before!!
NORMAL TERMINATE THREAD!!
F s_pAiMeDBClient Adr:0000016DC39CA590 
F m_pTCPSock Adr:0000016DC376E290
22/03/06 17:19:37 AimeLog Result:0

**Comment by Sucareto** [comment]
上传[ReaderTest](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/tools/ReaderTest/ReaderTest.ino)到读卡器或者使用其他方法读出AIC的idm，写入到felica.txt，然后启用segatools自带的模拟读卡器刷卡有没有这种问题？
看日志，感觉是游戏程序或服务器的问题。
