### ISSUE TITLE
Arduino Uno & Raspberry Pi Pico 无反应

### ISSUE THREAD

**Issue by jasyelr2** [Sucareto/Arduino-Aime-Reader#8]
使用硬件: Arduino Uno (ATMega328p) (国产, CH340) & Raspberry Pi Pico
SDBT测试菜单中 Aime 读卡器 在1.2秒后显示BAD, inject.exe 显示 "ERROR(3) #6507 NFC R/W Initialize Fault."

波特率38400, COM12
ReaderTest.ino 上传到 Uno 和 Pico 都可以正常读卡 (串口监视器有显示)
Uno RX灯有闪烁, TX看似沒有 (Pi Pico无TXRX灯)

发送DTR/RTS之后一样没反应

Pi Pico 是用这个Arduino核心(https://github.com/earlephilhower/arduino-pico)

同一個步骤在用Arduino Pro Micro完全正常, 可读卡

**Comment by Sucareto** [comment]
使用最新代码，检查`high_baudrate`变量的状态，如果是SDBT，`high_baudrate`应该设置为`false`。
如果仍然没反应，可以尝试使用串口调试工具手动发包看看有没有回复？

**Comment by jasyelr2** [comment]
SDHD cvt COM4 Eltima Serial Port Monitor抓包, baud 38400

32u4 正常读卡
[32u4_i2c_com4.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8749483/32u4_i2c_com4.zip)

不能读卡
[328p_com4.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8749481/328p_com4.zip)
[pico_com4.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8749482/pico_com4.zip)


Pico代码
[Arduino-Aime-Reader_rp2040.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8749486/Arduino-Aime-Reader_rp2040.zip)

**Comment by Sucareto** [comment]
代码检查了，应该是没问题的。
检查了 328p 和 pico 的串口数据，发现都是波特率设置为`115200`了，单片机没有回复。

看了 [pico 的文档](https://arduino-pico.readthedocs.io/en/latest/serial.html)，`Serial.begin(38400);`设置波特率可能没有效果，在设备管理器里面手动设置对应的波特率再试下。
代码里的：
`SerialDevice.begin(high_baudrate ? 115200 : 38400);`
改为：
`SerialDevice.begin(38400);`
再上传吧。

可以使用串口调试工具，手动发送数据包确认单片机是否可以正确回复，我在使用 `Serial Port Utility` 进行调试。
数据包的结构可以参考 [Example.txt](https://github.com/Sucareto/Arduino-Aime-Reader/blob/main/doc/Example.txt)。

这里提供几个示例，每行一条，可能需要删掉空格：
```
E0 05 00 01 62 00 68
E0 05 08 04 F5 00 06
E0 0B 00 05 54 06 57 43 43 46 76 32 35
E0 0B 00 06 50 06 60 90 D0 CF 06 32 F5 54
E0 06 00 1F 40 01 03 69
E0 05 00 20 42 00 67
```
以 HEX 而不是 Text 方式发送和接收，检查是否有回复？

**Comment by jasyelr2** [comment]
Uno和Pico手动发数据可以正确回复 (baud 38400)

发現不論在Device Manager內 baud 设置甚麼 SDHD 都会用115200打開COM4 (config_cvt.json "high_baudrate" : false)

试过Arduino方 ``Serial.begin(115200);`` 再由SDHD打开也没反应 (也试过 ``Serial.begin(38400);`` 由打开 SDBT 同样没反应)
把 amdaemon.exe / aimeReaderHost.exe 送到com4的 hex 手动送一次又会有正常回复
![image](https://user-images.githubusercontent.com/102594264/170120770-ad86ff82-9286-46bb-8464-47dc91863a97.png)

我也不能理解

[抓包.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8765729/default.zip)

**Comment by jasyelr2** [comment]
![image](https://user-images.githubusercontent.com/102594264/170119260-29a9170d-a66f-4fea-a558-9715b05aa4d4.png)

**Comment by Sucareto** [comment]
奇怪了...手动发送能正常回复的话，单片机和程序都是没问题的。
可能问题是出在 amdaemon.exe / aimeReaderHost.exe 上？
尝试更换别的游戏本体或更换其他版本的 amdaemon.exe？
不清楚 Raspberry Pi Pico，但如果你的 Arduino Uno 是使用 cH340 串口芯片，那 SDEZ 应该是没问题的。
我在 SDEZ 测试了 NodeMCU 1.0 和 NodeMCU-32S，都是使用的 CH340，驱动来自这里：[CH341SER.EXE](http://www.wch.cn/downloads/CH341SER_EXE.html)。

**Comment by jasyelr2** [comment]
[sddt_115200.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8806775/sddt_115200.zip)
下了 SDDT 1.35 试试
開之前COM1 (baud 115200)发DTR-RTS, amdaemon之后发没反应
(我怀疑windows是不是在serial有防火墙挡了, 但证明不了)

SDEZ 太大下不了

**Comment by Sucareto** [comment]
看到的确以正确的波特率打开了，但还是没有回复。
上传程序完成后，断电重新连接开发板，不要发送DTR-RTS，直接用串口调试工具发包看看。
如果有回复，那就是不需要DTR-RTS，这时候断开串口调试工具，开游戏程序看看。
如果还是不行，那我也不清楚什么原因了，可能是真的不支持吧...

**Comment by ghost** [comment]
> [sddt_115200.zip](https://github.com/Sucareto/Arduino-Aime-Reader/files/8806775/sddt_115200.zip) 下了 SDDT 1.35 试试 開之前COM1 (baud 115200)发DTR-RTS, amdaemon之后发没反应 (我怀疑windows是不是在serial有防火墙挡了, 但证明不了)
> 
> SDEZ 太大下不了

短接328p rst到vcc，问题解决
